# Generated by Django 5.2.6 on 2025-10-01 14:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_logdenuncia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='subcategoria',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='denuncia',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Denúncia', 'verbose_name_plural': 'Denúncias'},
        ),
        migrations.AlterModelOptions(
            name='logdenuncia',
            options={'ordering': ['-data_acao'], 'verbose_name': 'Log de Denúncia', 'verbose_name_plural': 'Logs de Denúncias'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='icone',
        ),
        migrations.AddField(
            model_name='categoria',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se a categoria está ativa para uso'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibição da categoria'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='data_previsao_resolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Resolução'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='data_resolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Resolução'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='observacoes_internas',
            field=models.TextField(blank=True, help_text='Observações para uso da equipe administrativa', null=True, verbose_name='Observações Internas'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='ponto_referencia',
            field=models.CharField(blank=True, help_text='Ponto de referência próximo (opcional)', max_length=255, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='resolucao',
            field=models.TextField(blank=True, help_text='Descrição de como o problema foi resolvido', null=True, verbose_name='Solução Aplicada'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='titulo',
            field=models.CharField(default=True, help_text='Título resumido do problema', max_length=200, verbose_name='Título da Denúncia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logdenuncia',
            name='dados_anteriores',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores'),
        ),
        migrations.AddField(
            model_name='logdenuncia',
            name='dados_novos',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados Novos'),
        ),
        migrations.AddField(
            model_name='logdenuncia',
            name='tipo_acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('ATUALIZACAO', 'Atualização'), ('STATUS', 'Alteração de Status'), ('PRIORIDADE', 'Alteração de Prioridade'), ('RESOLUCAO', 'Resolução'), ('COMENTARIO', 'Comentário')], default=False, max_length=20, verbose_name='Tipo de Ação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição opcional da categoria', null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='denuncias.categoria', verbose_name='Categoria do Problema'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='contato',
            field=models.CharField(blank=True, help_text='Telefone ou e-mail para retorno (opcional)', max_length=100, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='descricao',
            field=models.TextField(help_text='Descreva o problema em detalhes', verbose_name='Descrição Detalhada'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='endereco',
            field=models.CharField(default=False, help_text='Endereço ou local onde ocorreu o problema', max_length=255, verbose_name='Localização'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='foto',
            field=models.ImageField(blank=True, help_text='Faça upload de uma foto que mostre o problema', null=True, upload_to='denuncias/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'], message='Somente imagens JPG, JPEG, PNG ou GIF são permitidas')], verbose_name='Foto do Problema'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='protocolo',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Número do Protocolo'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('RECEBIDA', 'Recebida'), ('EM_ANALISE', 'Em Análise'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDA', 'Resolvida'), ('ARQUIVADA', 'Arquivada')], default='RECEBIDA', max_length=20, verbose_name='Status da Denúncia'),
        ),
        migrations.AlterField(
            model_name='logdenuncia',
            name='acao',
            field=models.CharField(max_length=255, verbose_name='Descrição da Ação'),
        ),
        migrations.AlterField(
            model_name='logdenuncia',
            name='data_acao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação'),
        ),
        migrations.AlterField(
            model_name='logdenuncia',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Ação'),
        ),
        migrations.AlterField(
            model_name='logdenuncia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_denuncias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AddIndex(
            model_name='denuncia',
            index=models.Index(fields=['status'], name='denuncias_d_status_33bbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='denuncia',
            index=models.Index(fields=['prioridade'], name='denuncias_d_priorid_6c46c8_idx'),
        ),
        migrations.AddIndex(
            model_name='denuncia',
            index=models.Index(fields=['data_criacao'], name='denuncias_d_data_cr_6a1bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='denuncia',
            index=models.Index(fields=['categoria'], name='denuncias_d_categor_573a04_idx'),
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
