# Generated by Django 5.2.6 on 2025-10-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0005_alter_denuncia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('NÃO_ATRIBUIDO', 'Aguardando Atribuição'), ('RECEBIDA', 'Recebida'), ('EM_ANALISE', 'Em Análise'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDA', 'Resolvida'), ('ARQUIVADA', 'Arquivada')], default='NÃO_ATRIBUIDO', max_length=20, verbose_name='Status da Denúncia'),
        ),
    ]
