# Generated by Django 5.2.6 on 2025-10-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0007_denuncia_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdenuncia',
            name='tipo_acao',
            field=models.CharField(choices=[('NÃO_ATRIBUIDO', 'Aguardando Atribuição'), ('RECEBIDA', 'Recebida'), ('EM_ANALISE', 'Em Análise'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDA', 'Resolvida'), ('ARQUIVADA', 'Arquivada')], max_length=20, verbose_name='Tipo de Ação'),
        ),
    ]
