# Generated by Django 5.2.6 on 2025-10-06 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0008_alter_logdenuncia_tipo_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='foto',
            field=models.ImageField(blank=True, help_text='Faça upload de uma foto que mostre o problema', null=True, upload_to='denuncias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'], message='Somente imagens JPG, JPEG, PNG ou GIF são permitidas')], verbose_name='Foto do Problema'),
        ),
    ]
