name: Django CI


on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        
        python-version: ["3.11"] 

    steps:
      # 1. Clona o seu repositório para dentro da máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura a versão do Python (de acordo com a matriz acima)
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Etapa de "Build": Instala as dependências
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. Etapa de "Testes Automatizados": Roda os testes do Django
      - name: Run Tests
        run: |
          python manage.py test